name: deploy-book

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip # Implicitly uses requirements.txt for cache key

    - name: Install dependencies
      run: pip install -r book/requirements.txt

    # (optional) Cache your executed notebooks between runs
    # if you have config:
    # execute:
    #   execute_notebooks: cache
    - name: cache executed notebooks
      uses: actions/cache@v4
      with:
        path: book/_build/.jupyter_cache
        key: jupyter-book-cache-${{ hashFiles('book/requirements.txt') }}

    # Build the book
    - name: Build the book
      run: |
        cp -r assignments book/assignments
        python -m venv .venv
        pip install .
        python -m ipykernel install --user --name datascipsych
        jupyter-book build book

    # Upload the book's HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "book/_build/html"

    # Deploy the book's HTML to GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
